import type { ConnectionRequestDataType } from './connections.types';

export const CONNECTION_REQUEST_TYPE: Record<ConnectionRequestDataType, number> = {
  wifi: 0x77_69_66_69,
  frame: 0x66_72_61_6d,
};
export const CONNECTION_REQUEST_EOL_INFO = 0x45_4f_4c_00;
export const CONNECTION_REQUEST_TYPE_INFO_LENGTH = 4;
export const CONNECTION_REQUEST_SIZE_INFO_LENGTH = 4;
export const CONNECTION_REQUEST_EOL_INFO_LENGTH = 4;

export const CONNECTION_REQUEST_FRAME_TYPE_LENGTH = 1;
export const CONNECTION_REQUEST_FRAME_TEMPO_LENGTH = 1;
export const CONNECTION_REQUEST_FRAME_COLOR_LENGTH = 1;

export const CONNECTION_REQUEST_INFO_LENGTH =
  CONNECTION_REQUEST_TYPE_INFO_LENGTH +
  CONNECTION_REQUEST_SIZE_INFO_LENGTH +
  CONNECTION_REQUEST_EOL_INFO_LENGTH;

const TRAILING_ZERO_LENGTH = 1;
export const SSID_MAX_LENGTH = 32 + TRAILING_ZERO_LENGTH;
export const PASSWORD_MAX_LENGTH = 64 + TRAILING_ZERO_LENGTH;
